#ifndef SEESAW_CONFIG_H
#define SEESAW_CONFIG_H

#define CONFIG_VERSION 0x55

#define CONFIG_ADC 0

#define CONFIG_DAC 0

#define CONFIG_INTERRUPT 0

#define CONFIG_SERCOM0 0
#define CONFIG_SERCOM1 0
#define CONFIG_SERCOM2 0
#define CONFIG_SERCOM3 0
#define CONFIG_SERCOM4 0
#define CONFIG_SERCOM5 1

#define CONFIG_I2C_SLAVE 1
#define CONFIG_I2C_SLAVE_SERCOM SERCOM3
#define CONFIG_I2C_SLAVE_HANDLER SERCOM3_Handler
#define CONFIG_I2C_SLAVE_IRQn SERCOM3_IRQn

#define CONFIG_I2C_SLAVE_PIN_SDA 5
#define CONFIG_I2C_SLAVE_PIN_SCL 6

#define CONFIG_I2C_SLAVE_ADDR 0x49

#define CONFIG_SERCOM_UART_PIN_RX 0
#define CONfIG_SERCOM_UART_PIN_TX 1
#define CONFIG_SERCOM_UART_PAD_TX UART_TX_PAD_2
#define CONFIG_SERCOM_UART_PAD_RX SERCOM_RX_PAD_3

#define CONFIG_SERCOM_UART_BAUD_RATE 9600
#define CONFIG_SERCOM_UART_CHAR_SIZE UART_CHAR_SIZE_8_BITS

#define CONFIG_SERCOM_UART_PARITY SERCOM_NO_PARITY

#define CONFIG_SERCOM_UART_STOP_BIT SERCOM_STOP_BIT_1

#define CONFIG_NUM_AO (1 + CONFIG_ADC + CONFIG_DAC + CONFIG_INTERRUPT + CONFIG_SERCOM0 + CONFIG_SERCOM1 + CONFIG_SERCOM2 + CONFIG_SERCOM3 + CONFIG_SERCOM4 + CONFIG_SERCOM5 + CONFIG_I2C_SLAVE)

#endif